services:
  server:
    build: 
      context: ./server/
      dockerfile: Dockerfile
    container_name: express-backend
    ports:
      - "3000:3000"

  client:
    build: 
      context: ./client/
      dockerfile: Dockerfile
    container_name: react-frontend
    ports:
      - "5173:5173"
